<?php 

// VAMOS TRABALHAR COM A DECLARAÇÃO DE VARIÁVEIS NO ESTILO CAMEL CASO - COMO ABAIXO
$anoNascimento = 1900;
$nomeCompleto = "";

// NÃO DEVEMOS TRABALHAR COM NÚMEROS NO INÍCIO DA VAR
$nome1 = "João";
$1nome = ""; #ERRADO

?>