<?php 

$nome = "Adriano";

echo $nome;
echo "<br/>";

//UNSET É O COMANDO DO PHP RESPONSÁVEL POR LIMPAR O VALOR DA VARIÁVEL, CASO EU TENHA MÚLTIPLAS VARIAVEIS E EU QUEIRA LIMPAR TODAS, DEVO COLOCAR O UNSET(E AQUI DENTRO COLOCAR TODAS AS VARS, SEPARADAS POR VÍRGULA)
unset($nome);

echo $nome;

?>